Add Nerfels and SDF-based RGBD tracking
zubair-irshad/Awesome-Implicit-NeRF-Robotics pull request #2
Opened 2022-06-09 16:52 UTC by kudo1026

2022-06-09 18:02 UTC, zubair-irshad commented on README.md
> +* "SDF-based RGB-D Camera Tracking in Neural Scene Representations", *ICRA Workshop, 2022*. [[Paper](https://neural-implicit-workshop.stanford.edu/assets/pdf/bruns.pdf)]
I think this should be under SLAM. Could you please update?

2022-06-09 18:03 UTC, zubair-irshad requested changes
I think this should be under SLAM. Could you please update?

* "SDF-based RGB-D Camera Tracking in Neural Scene Representations", *ICRA Workshop, 2022*. [[Paper](https://neural-implicit-workshop.stanford.edu/assets/pdf/bruns.pdf)]

2022-06-09 18:39 UTC, kudo1026 commented
To me, SLAM means the algorithm needs to figure out both pose and map at the same time (preferably in real time). Both of these two works assume pre-computed implicit representations and focus on the pose optimization. Similarly, LENS should be moved to "pose estimation". 

On another note, iSDF (at its current state) may not qualify for SLAM either because they actually use gt poses (I talked the author, he said they tried to learn poses at the same time, but not successful). 

Let me know what you think.

2022-06-09 19:16 UTC, zubair-irshad commented
Makes sense, thanks for the clarification. Maybe move them to their separate own thread titled 'Camera Pose optimization/Tracking' or a related name? 

I thought earlier about merging 6D Object Pose Estimation and camera Pose estimation/optimization; I think robotic folks like to have a separate thread/line of works for 6D Object Pose Estimation including instance-based/category-level works etc. 

Let me know what you think!

2022-06-10 22:01 UTC, kudo1026 commented
What's the difference between _object_ and _camera_ pose optimization? Aren't they just inverse to each other?

2022-06-15 19:50 UTC, zubair-irshad commented
For a single object like [SRN dataset](https://github.com/vsitzmann/scene-representation-networks#data), yes this seems to be true (there are inverse to each other). For multi-object scenarios, the camera pose remains same but each object's rotation and translation w.r.t the camera changes (also used to fit a tighter bounding box around object of interest). Particularly evident for robotics datasets and dynamic moving objects in case of cars for Kitti. Here is a tutorial for [6D object pose](https://haosulab.github.io/ml-meets-geometry/WI21/Lectures/L12_6D_Pose_Estimation_II.pdf). 

[Nerf-Pose](https://arxiv.org/pdf/2203.04802.pdf) is trying to solve the object-pose estimation problem given GT camera poses whereas [Nerfels](https://arxiv.org/pdf/2206.01916.pdf) for camera pose. IMHO, Nerfels and other could fit under both categories.

2022-12-03 17:26 UTC, zubair-irshad commented
Closing this. Please see this [PR](https://github.com/zubair-irshad/Awesome-Implicit-NeRF-Robotics/commit/32f12a1ab4428053ada8ee01383fab426901e824). SLAM currently is loosely defined to incorporate camera pose optimization/tracking works but feel free to open sub-threads in future to expand this or move this sub-work into it's own thread. Thanks for your contribution

2022-12-03 17:26 UTC, closed without merging